# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocemr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunizationlog',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='immunizationlog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vac',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='vac',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vac',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vacnote',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='vacnote',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vacnote',
            name='type',
        ),
        migrations.DeleteModel(
            name='ImmunizationLog',
        ),
        migrations.DeleteModel(
            name='Vac',
        ),
        migrations.DeleteModel(
            name='VacNote',
        ),
        migrations.DeleteModel(
            name='VacType',
        ),
    ]
