# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocemr', '0003_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='breastfeedingProblems',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='deliveryDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pmtct',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='postpartumFollowUp',
            field=models.NullBooleanField(default=None),
        ),
    ]
