# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-26 23:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocemr', '0004_preganacy_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=64)),
                ('content', models.TextField(default=b'')),
            ],
        ),
    ]
